on:
  push:
    branches:
      - main

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - run: npm test
      - name: Collect coverage for client
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: client